### ISSUE TITLE
Stable now longer points to version compatible with stable OpenProject 

### ISSUE THREAD

**Issue by bjornblissing** [opf/openproject-documents#25]
The stable tag of OpenProject has been updated to 4.0. 
The stable tag of openproject-documents plugin do not support version 4.0.

**Comment by ulferts** [comment]
@bjornblissing, I merged 4.0 into stable with https://github.com/opf/openproject-documents/commit/c58740c715c6947eb24e442bf50d3cbf5f54183f. Isn't that what you mean?

It is the stable branch (as opposed to a tag) but I think that this should not make a difference.

**Comment by bjornblissing** [comment]
Sorry, I must have done something wrong yesterday. I merged your stable branch with my own and for some reason I did not get the updated `lib/open_project/documents/version.rb` file in my merge. It was probably due to some mistake on my part. When I repeated the same merge today it works as expected.
